### ISSUE TITLE
restructure peering pages

### ISSUE THREAD

**Issue by liske** [dd-ix/presence#10]
IMHO the peering pages need some changes:

- peers don't need tiles but we need a table for a quick overview about orgs, their ASN, their ports and if the are peering with the RS (this is important for interested parties)
  **Update** The table should be generated from the entries in *IXP Manager* which provides an export in [Euro-IX JSON Schema](https://github.com/euro-ix/json-schemas)
  Example: [BCIX member export](https://www.bcix.de/ixp/api/v4/member-export/ixf)

- we should also have a location page with details about the data center locations and the available carriers

Small mockup:

![image](https://github.com/dd-ix/presence/assets/372458/cfdeba0c-a9c3-4a23-bfea-fa712488766f)

**Comment by MarcelCoding** [comment]
@liske Take a look at the version in the master branch.

**Comment by liske** [comment]
Thanks, fixed by fa80f95c567521c8db488fee795fa2dec4b0ad13.
