### ISSUE TITLE
Tiles for contact page?

### ISSUE THREAD

**Issue by liske** [dd-ix/presence#11]
The contact page might contain different tiles for contact requests:
- general contact
- peering requests
- press

And the postal address. Some tiling/grid/flexbox view might be nice, but IMHO this is not possible with the markdown, yet.

![image](https://github.com/dd-ix/presence/assets/372458/22f5004f-c7ad-4a69-854c-739a63ffcf53)

**Comment by revol-xut** [comment]
done
