### ISSUE TITLE
markdown lists layout

### ISSUE THREAD

**Issue by liske** [dd-ix/presence#12]
Markdown lists (i.e. Peering & Joining Policy) look broken. It seems to be triggered by an unnecessary paragraph element inside the list items (the first two list items in Requirements where manually stripped from the `<p>` within the browser) :

![image](https://github.com/dd-ix/presence/assets/372458/03ab79f9-cedc-4c6b-9a6d-eb8bb96e0fea)

## Update

It seems to be triggered by the empty line(s) after the list:

- a single empty line (in `## Responsibilities and Guarantees`) will **not** break the list but the paragraph after the list does not have the required spacing to the list
- using two empty lines will fix the spacing but break the list (additional `<p>` elements)

**Comment by MarcelCoding** [comment]
not really fixed, just because of your workaround in the markdown files
