### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by MarcelCoding** [dd-ix/presence#15]
# Feedback Round 1

## Content
- [x] alle Links testen - keine Toten Links
- [x] Hackday 01 Atrikel schreiben
- [x] Impressum fixen - stimmt das so aktuell?

## Design
- [x] Text größer
- [x] Text Font
- [x] Menü größer machen
- [x] Bisschen Mehr Farbe und Colorscheme
- [x] Mehr Bilder unsplash.com + Icons Text auf dem Screen durch Bilder Strechen - z.B. 
- [x] Ripe DB in Team Site pro Person rein machen
- [x] LinkedIn als Social einbauen
- [x] Team Boxen alle gleich groß
- [x] Peering Policy Kasten Background image
- [x] alle Grafiken/Icons in die cloud packen
- [x] Contact Page
- [x] DD-IX Überschrift Größer
- [x] Keep Local Traffic Local Lime und größer
- [x] Handy Ansicht mit den neuen Icons im Text
- [x] favicon

# Feedback Round 2

## Content
- [x] History Artikel von Sandra

## Design
- [x] Turning Section on Frontpage to Links
- [x] Tags for News Articels #16 (Melo Change request with "and" and "or")
- [x] Testing different Backgrounds
- [x] Contact Shit Emojis
- [x] Safari cannot handle icons
- [x] Logo doesn't show up on safari
- [x] Impressum <br>
- [x] Mobile is absolut cluster fuck
   - [x] No Hamburger or Sidebar  -> Zero Navigation possbile

**Comment by waehlisch** [comment]
Die Icons im Menue wuerde ich weglassen. Die sind zu viel.
